# Generated by Django 5.1.1 on 2024-10-09 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_discountcategory_alter_category_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcategory',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='category.category'),
            preserve_default=False,
        ),
    ]
